# Generated by Django 5.2.1 on 2025-06-05 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_contato_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='telefone',
            new_name='phone',
        ),
    ]
