# Generated by Django 5.2.1 on 2025-06-10 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_category_contact_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
