# Generated by Django 5.2.1 on 2025-06-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
